// Code generated by "stringer -type=unaryOperator"; DO NOT EDIT.

package refine

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[unaryMinus-0]
	_ = x[unaryPlus-1]
	_ = x[unaryNot-2]
	_ = x[unaryDereference-3]
}

const _unaryOperator_name = "unaryMinusunaryPlusunaryNotunaryDereference"

var _unaryOperator_index = [...]uint8{0, 10, 19, 27, 43}

func (i unaryOperator) String() string {
	if i < 0 || i >= unaryOperator(len(_unaryOperator_index)-1) {
		return "unaryOperator(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _unaryOperator_name[_unaryOperator_index[i]:_unaryOperator_index[i+1]]
}
